CREATE TABLE spotify_songs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  artist VARCHAR(255) DEFAULT NULL,
  layer1 VARCHAR(255) DEFAULT NULL,
  layer2 VARCHAR(255) DEFAULT NULL,
  spotify_id VARCHAR(255) DEFAULT NULL,
  track_name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO team6_ad.spotify_songs (`id`,`artist`,`layer1`,`layer2`,`track_name`,`spotify_id`) VALUES
(1,'Limp Bizkit','Metal','00s Metal Classics','Take A Look Around','2avKuMN2QXkaG9vvHa2JLt'),
(2,'Mudvayne','Metal','00s Metal Classics','Happy?','0INUE1K7cEiE8VH63Rv5RJ'),
(3,'Type O Negative','Metal','00s Metal Classics','Love You to Death','5NhOIUwQ1v10mnPki6Qw3I'),
(4,'Lamb of God','Metal','00s Metal Classics','Omerta','4Vb5Y6RQztThqqqFre24wL'),
(5,'blessthefall','Metal','2023 Metalcore Playlist','Wake The Dead','7cLEpyYMAgQh3x0oX6scp3'),
(6,'Bilmuri, Mitchell Tenpenny','Metal','2023 Metalcore Playlist','ALL GAS','2THiSfWbMGD9l2g2Ircxga'),
(7,'Asking Alexandria','Metal','2023 Metalcore Playlist','Psycho','6s3MpvQ1ulwrTuRhBgv0Eu'),
(8,'Hall of the Elders','Metal','2023 Metalcore Playlist','Yeast Unleashed in the East','7jpYj9IhDCyYANbD35usE7'),
(9,'Veil Of Maya','Metal','2023 Metalcore Playlist','Red Fur','1jj922BgyJexH19yoHd23L'),
(10,'Red Hot Chili Peppers','Rock','90 Rock Anthems','Scar Tissue','6sbE8RyxI6oj54IijF6dLE'),
(11,'4 Non Blondes','Rock','90 Rock Anthems','What\'s Up?','0jWgAnTrNZmOGmqgvHhZEm'),
(12,'Beck','Rock','90 Rock Anthems','Loser','5NTZM8YYeKM2YsGSffVIge'),
(13,'Nirvana','Rock','90 Rock Anthems','Come As You Are','2RsAajgo0g7bMCHxwH3Sk0'),
(14,'Red Hot Chili Peppers','Rock','90 Rock Anthems','Give It Away','0uppYCG86ajpV2hSR3dJJ0'),
(15,'Teen Jesus and the Jean Teasers','Rock','All New Rocks','I Used To Be Fun','7sCMZKSjZbx563QSkqxTqC'),
(16,'RØRY','Rock','All New Rocks','hurt myself','0hA21a7LBM161F57QDR2IH'),
(17,'YONAKA','Rock','All New Rocks','By The Time You\'re Reading This','0uuxAXS1X7kH0WjC0nD6q9'),
(18,'BRKN LOVE, DYLYN','Rock','All New Rocks','Liberate Me II','0gx0mxHF6gewK9FZL9mwi9'),
(19,'BOYS LIKE GIRLS','Rock','All New Rocks','THE OUTSIDE','6y8p0dDbtPOfAPoTdNv2xi'),
(20,'John Denver','Country','Best Country Songs','Take Me Home, Country Roads','1YYhDizHx7PnDhAhko6cDS'),
(21,'Sam Hunt','Country','Best Country Songs','Break Up In A Small Town','7aftSOGSOpSoIlVAQVBb71'),
(22,'Jason Aldean','Country','Best Country Songs','Big Green Tractor','4KAzYqfcijCSZa2P3etHoM'),
(23,'Blake Shelton','Country','Best Country Songs','Came Here to Forget','1N7qGCKRRnvjoy8MGyHgpS'),
(24,'Charles Kelley','Country','Best Country Songs','The Driver','1LDeuD3jbSpHucsd0nOt6t'),
(25,'Kevin Garrett','Country','Best Country Songs','Little Bit of You','6vb40FRWv3PNK7eqBHXUFz'),
(26,'Bruno Mars','EDM','Best EDM Songs of All The Times','That\'s What I Like - Alan Walker Remix','1KtU0WCq472KzqCXgMOxkS'),
(27,'Calvin Harris','EDM','Best EDM Songs of All The Times','I Need Your Love (feat. Ellie Goulding)','05SBRd4fXgn8FX7bf8BCAE'),
(28,'Martin Garrix','EDM','Best EDM Songs of All The Times','In the Name of Love','23L5CiUhw2jV1OIMwthR3S'),
(29,'Major Lazer','EDM','Best EDM Songs of All The Times','Light It Up - Remix','5KrXCECYQHCM52GdBViNQr'),
(30,'Bipolar Sunshine, DJ Snake','EDM','Best EDM Songs of All The Times','Middle','0g5EKLgdKvNlln7TNqBByK'),
(31,'Limp Bizkit','Rock','Best of Rock 2000','Hot Dog','6Zj3YsYfj8YTY9aGMDnpn8'),
(32,'3 Doors Down','Rock','Best of Rock 2000','Kryptonite','6ZOBP3NvffbU4SZcrnt1k6'),
(33,'Robert Glasper','Rock','Best of Rock 2000','Maiden Voyage / Everything In Its Right Place','0jyXW8hxeIzX4QwznqVT0E'),
(34,'Linkin Park','Rock','Best of Rock 2000','A Place For My Head','5rAxhWcgFng3s570sGO2F8'),
(35,'U2','Rock','Best of Rock 2000','Stuck In A Moment You Can\'t Get Out Of','1klDPm7SfsS32hl7KHV9iy'),
(36,'The Cramps','Punk','Classic Punk','Goo Goo Muck','3EEd6ldsPat620GVYMEhOP'),
(37,'Blondie','Punk','Classic Punk','One Way Or Another','1gKmnrz6SzJlGMNRKBLx1V'),
(38,'Black Flag','Punk','Classic Punk','Six Pack','5Og9VyCOfxmZCuv1UhIyxE'),
(39,'Iggy Pop','Punk','Classic Punk','Lust For Life','21YxK0klhpfLW8budkJaMF'),
(40,'New York Dolls','Punk','Classic Punk','Personality Crisis','4AwKXevZmsTNa3KZVj3rzl'),
(41,'Barenaked Ladies','Country','Classic Road Trip Songs','If I Had $1,000,000','0KeDuUqEX3P0cKzRD5pEom'),
(42,'The Cars','Country','Classic Road Trip Songs','Just What I Needed','4alHo6RGd0D3OUbTPExTHN'),
(43,'Styx','Country','Classic Road Trip Songs','Come Sail Away','0PsbWiVtix5FoTZ1s00mEl'),
(44,'Huey Lewis & The News','Country','Classic Road Trip Songs','The Power Of Love','2olVm1lHicpveMAo4AUDRB'),
(45,'AC/DC','Country','Classic Road Trip Songs','You Shook Me All Night Long','2SiXAy7TuUkycRVbbWDEpo'),
(46,'The Romantics','Country','Classic Road Trip Songs','What I Like About You','6NdcSEhpGGAYXNnnhGS2s6'),
(47,'The Who','Rock','Classic Rock','Baba O\'Riley - ConfidentialMX Remix','5iq0Tela3gm73ZW72XZ5dm'),
(48,'Nirvana','Rock','Classic Rock','Come As You Are','2RsAajgo0g7bMCHxwH3Sk0'),
(49,'Foo Fighters','Rock','Classic Rock','Everlong','5UWwZ5lm5PKu6eKsHAGxOk'),
(50,'Heart','Rock','Classic Rock','Barracuda','4KfSdst7rW39C0sfhArdrz'),
(51,'Red Hot Chili Peppers','Rock','Classic Rock','Californication','48UPSzbZjgc449aqz8bxox'),
(52,'Oliver Tree, Robin Schulz','EDM','Club Beats 2023','Miss You','73vIOb4Q7YN6HeJTbscRx5'),
(53,'Bebe Rexha, David Guetta','EDM','Club Beats 2023','I\'m Good (Blue)','4uUG5RXrOk84mYEfFvj3cK'),
(54,'James Hype, Miggy Dela Rosa','EDM','Club Beats 2023','Ferrari','4zN21mbAuaD0WqtmaTZZeP'),
(55,'CLARK S, PASSIK','EDM','Club Beats 2023','Paralyzed','5sAmYBx0Rkt9pguQNKXUSZ'),
(56,'CØDE, Sammy Boyle','EDM','Club Beats 2023','Don\'t Call Me Up','3fd8jNH7Ng1LaQ7PpCn22J'),
(57,'Lee Brice','Country','Country Love Songs','Hard To Love','6E9V9TRlVOLjenGjHemzEH'),
(58,'Logan Mize','Country','Country Love Songs','Better Off Gone','6IqUm14MgoKbwt6jdGBikH'),
(59,'Chase Rice','Country','Country Love Songs','Eyes On You - Acoustic','1YGSgLkGrLzexPAw2AJBpJ'),
(60,'Cole Swindell','Country','Country Love Songs','Middle of a Memory','38gZVjeaeR3gcnCzziAxBm'),
(61,'Chris Bandi','Country','Country Love Songs','Man Enough Now','1DKUs6bsxsDtnbykNSiGxB'),
(62,'Chris Lane, Lauren Alaina','Country','Country Popular 2023','Dancin\' In The Moonlight (feat. Lauren Alaina)','0pnKcAh5binHOP9HexWwnZ'),
(63,'Jason Aldean','Country','Country Popular 2023','Heaven','7pcfqF4wUhxvfoMqzXQYar'),
(64,'Julia Cole','Country','Country Popular 2023','He Got the Best of Me','5brBLjXJuQ1leaH5VAGBGq'),
(65,'Audra Mae','Country','Country Popular 2023','Little Sparrow','2StnRp0wOEEQ5LpuIrvXcZ'),
(66,'Dylan Marlowe','Country','Country Popular 2023','Drivers License','5kP970YG6XuXHfXZiTW5sk'),
(67,'Far East Movement','Pop','Dance Pop','Like A G6','5AyL2kgLtTWEu3qO3B9SqK'),
(68,'Calvin Harris, Ellie Goulding','Pop','Dance Pop','I Need Your Love (feat. Ellie Goulding)','05SBRd4fXgn8FX7bf8BCAE'),
(69,'Bebe Rexha, David Guetta','Pop','Dance Pop','I\'m Good (Blue)','4uUG5RXrOk84mYEfFvj3cK'),
(70,'Cardi B, DJ Snake, Ozuna, Selena Gomez','Pop','Dance Pop','Taki Taki (with Selena Gomez, Ozuna & Cardi B)','4w8niZpiMy6qz1mntFA5uM'),
(71,'Taylor Swift','Pop','Dance Pop','The Lucky One','5VQLMrWhailAhErKNUSnv1'),
(72,'Computorgirl, for all the emptiness','EDM','EDM BANGERZ','dead inside','7J0iDfnknuDuMRg57sDXqd'),
(73,'C-Devastator','EDM','EDM BANGERZ','Put You Left Hand Up','4BlGFyfRO3cK03w7KSym8H'),
(74,'CONT4MIN4TED','EDM','EDM BANGERZ','So Easy','6lwCOvj2wMDz0TG95Z20jd'),
(75,'Carpente, Pepper Gomez','EDM','EDM BANGERZ','Because You Know','36Ynrpjx2PBvNFjABVSBUc'),
(76,'CONT4MIN4TED','EDM','EDM BANGERZ','Dreaming In Color','5Rad1223E8kAkEPYsXJ58v'),
(77,'Alika, Armin van Buuren, Punctual','EDM','EDM Gaming','On & On','6wLqNGHQIja6xqT0cfrzBB'),
(78,'AXMO, W&W','EDM','EDM Gaming','Ritmo De La Noche (Vamos A La Playa)','3APyTiWzqQtT8vd0kRz6lo'),
(79,'Don Diablo, Gabry Ponte','EDM','EDM Gaming','Sunglasses At Night','6eoY6XnhGFr3HInyECJdbx'),
(80,'James Hype, Major Lazer','EDM','EDM Gaming','Number 1','5HadIAY3Oray8VKuv3shgQ'),
(81,'Leony, Niklas Dee, Tokio Hotel, VIZE','EDM','EDM Gaming','Monsoon (feat. Tokio Hotel)','5KtDo0LvaAVjRXrIFrYgUF'),
(82,'Skan','EDM','EDM Workout','No Glory (feat. M.I.M.E & Drama B)','3xSyhYmk0s4ySQcluJWxp9'),
(83,'Calvin Harris','EDM','EDM Workout','Flashback','6A8llSO9QFF4djCCmuCrNu'),
(84,'Calvin HarrisEllie Goulding','EDM','EDM Workout','Miracle (with Ellie Goulding)','5eTaQYBE1yrActixMAeLcZ'),
(85,'Bebe RexhaDavid Guetta','EDM','EDM Workout','I\'m Good (Blue)','4uUG5RXrOk84mYEfFvj3cK'),
(86,'Invisible, The FifthGuys, The Late Night Project','EDM','EDM Workout','Sweet Child O\' Mine','0iRfffwrWG4TfNc65SpxDm'),
(87,'Judas Priest','Metal','Heavy Metal','Breaking the Law','2RaA6kIcvomt77qlIgGhCT'),
(88,'Korn','Metal','Heavy Metal','Freak On a Leash','6W21LNLz9Sw7sUSNWMSHRu'),
(89,'Godsmack','Metal','Heavy Metal','I Stand Alone','6eYUbXmncekAKMYZcsSkyD'),
(90,'Five Finger Death Punch','Metal','Heavy Metal','Bad Company','1UWGkn34CD31VQfdi4D8Zp'),
(91,'Exodus','Metal','Heavy Metal','The Toxic Waltz','5ZOOjqoCaUydmo8bxSdosj'),
(92,'Dr. Dre','Hip Hop','Hip Hop 90-20','The Next Episode','4LwU4Vp6od3Sb08CsP99GC'),
(93,'50 Cent','Hip Hop','Hip Hop 90-20','Candy Shop','5D2mYZuzcgjpchVY1pmTPh'),
(94,'Nate Dogg','Hip Hop','Hip Hop 90-20','Shake That (Remix)','0fGh0trRN1xz3s41r7V5ce'),
(95,'Nas & Damian \"Jr. Gong\" Marley','Hip Hop','Hip Hop 90-20','As We Enter','1hxcg5FRB5lZv5PdAThDpe'),
(96,'Makaveli','Hip Hop','Hip Hop 90-20','Me And My Girlfriend','7722WsrGPUvUMcfBR87nhc'),
(97,'2Pac','Hip Hop','Hip Hop Classic','California Love - Original Version','3ia3dJETSOllPsv3LJkE35'),
(98,'Nelly','Hip Hop','Hip Hop Classic','Hot In Herre','04KTF78FFg8sOHC1BADqbY'),
(99,'Snoop Dogg','Hip Hop','Hip Hop Classic','Drop It Like It\'s Hot','2NBQmPrOEEjA8VbeWOQGxO'),
(100,'Drake, Eminem, Kanye West, Lil Wayne','Hip Hop','Hip Hop Classic','Forever','5UsLjwBaTHBX4ektWIr4XX'),
(101,'Busta Rhymes','Hip Hop','Hip Hop Classic','Break Ya Neck','7gKgd0P3dAAePiSQQBqrlf'),
(102,'OutKast','Hip Hop','Hip Hop Dance Playlist','Hey Ya!','2PpruBYCo4H7WOBJ7Q2EwM'),
(103,'Lil Wayne','Hip Hop','Hip Hop Dance Playlist','6 Foot 7 Foot','1hvInhBgFlH88UaZrLJ43O'),
(104,'Kid Cudi','Hip Hop','Hip Hop Dance Playlist','Make Her Say','1JzC9MScDhIomsiRIZYJO8'),
(105,'JAY-Z','Hip Hop','Hip Hop Dance Playlist','Lucifer','05VHidqx1tV6V7MsCdAIby'),
(106,'Big Sean','Hip Hop','Hip Hop Dance Playlist','Dance (A$$)','4dMfcca0nQNXXj1etzeME4'),
(107,'Nico Salas','Hip Hop','Hip Hop Hits','Listen to your heart','6OaIKDrr0Jd8B5CSHlaJwG'),
(108,'Angelo Tulabing, Skulls Can Dream','Hip Hop','Hip Hop Hits','MAKE ME SMILE','2HPba1EOWJ1wNDfqeGUaAS'),
(109,'Blue City CDF, Pitch 92','Hip Hop','Hip Hop Hits','The Summit','4aXr5C57OoHwVCCsskM3K6'),
(110,'Oscar Smith','Hip Hop','Hip Hop Hits','FAITH DON\'T DIE','0q4x0qIRvDeC0PQ1atOGqE'),
(111,'Kushing','Hip Hop','Hip Hop Hits','Hyphy','7nEGDQldLoCg8A1VoZY711'),
(112,'Fat Joe','Hip Hop','Hip Hop Workout','All The Way Up','7Ezwtgfw7khBrpvaNPtMoT'),
(113,'Omar LinX','Hip Hop','Hip Hop Workout','Keep It Mello (feat. Omar LinX)','0Q3SC6kEhxYagDP3bFe5K9'),
(114,'Cardi B','Hip Hop','Hip Hop Workout','Money','2GGMabyHXnJmjY6CXhhB2e'),
(115,'Tyga','Hip Hop','Hip Hop Workout','VACATION','6q2uIyLqASSpv2SIv2ehWK'),
(116,'AJ Tracey,Headie One, Stormzy','Hip Hop','Hip Hop Workout','Ain\'t It Different (feat. AJ Tracey & Stormzy)','6NJfIydBMYrXvlaXsFxmc8'),
(117,'Norah Jones','Jazz','Jazz 2023','Don\'t Know Why','1zNXF2svmdlNxfS5XeNUgr'),
(118,'Michael Bublé','Jazz','Jazz 2023','Feeling Good','1AM8QdDFZMq6SrrqUnuQ9P'),
(119,'Angelina Jordan','Jazz','Jazz 2023','Bohemian Rhapsody','4dPKZJKJzPl4TEWLsMdohE'),
(120,'Angelina Jordan','Jazz','Jazz 2023','7th Heaven','4dtZRUQCZJFvykWMxxfbCt'),
(121,'Michael Bublé','Jazz','Jazz 2023','The Way You Look Tonight','4YGlRLe6TeBRiXFByBqldf'),
(122,'Glenn Miller','Jazz','Jazz Classic','In The Mood','6dZKWYSx5YBIme4SfpIHJ0'),
(123,'Ella Fitzgerald, Louis Armstrong','Jazz','Jazz Classic','Dream A Little Dream Of Me - Single Version','78MI7mu1LV1k4IA2HzKmHe'),
(124,'AntÃ´nio Carlos Jobim','Jazz','Jazz Classic','The Girl From Ipanema','6ZMrpXuvDO8T13QVrshXlL'),
(125,'John Coltrane','Jazz','Jazz Classic','My One And Only Love','0uPkCpuoERqrkBL06Art50'),
(126,'Louis Armstrong','Jazz','Jazz Classic','What A Wonderful World','29U7stRjqHU6rMiS8BfaI9'),
(127,'Francis Graden','Jazz','Jazz For Sleep','On A Clear Day','2rIuYJ81BdL5pukyDjhxj7'),
(128,'Anna Niva','Jazz','Jazz For Sleep','The End Of A Love Affair','121BsQV03zxG11taJmpnUe'),
(129,'Kristian Hart','Jazz','Jazz For Sleep','When Hearts Turn Blue','7nsHRk3Dbx5tj8ya1Vw1eF'),
(130,'Alexander Descartes','Jazz','Jazz For Sleep','In a sentimental mood','3gmQ3tklUt8IJixvO3jVAp'),
(131,'Tyler Marshall','Jazz','Jazz For Sleep','We\'ve Never Been Here','4ymZ6dNuL9uXOPKztxaGti'),
(132,'Novo Stella','Jazz','Jazz In The Rain','Feathers','3YvFRSz2nrV493DaCAEEBx'),
(133,'Michael Stylez & Co','Jazz','Jazz In The Rain','Forgiving','7aTGWdhRtlPx0FBF8IeAek'),
(134,'Magnolia','Jazz','Jazz In The Rain','Her Song','1ePnBDWTj8rvGAqsfKApk3'),
(135,'Lennie Weston','Jazz','Jazz In The Rain','Evening Rain','4tfNLlpSHpFvBsVufocJKn'),
(136,'Gillian Spencer Trio','Jazz','Jazz In The Rain','And All Is Well Now','116Z8pydjYsREn2LWk7El7'),
(137,'Chill Select, mvnitou','Jazz','Lofi Jazz','Telepathy','756ABsx2jb3gsJwBWfsYn1'),
(138,'Beatmund Noise, Chill Select, mariussax, Suede Wallet','Jazz','Lofi Jazz','Jenny\'s Coffee','3KbzR3m68Mpo4dSzLWUHpl'),
(139,'Billa Qause, Chill Select','Jazz','Lofi Jazz','Moonlight','5xNBDTbvLPe6PK4BKJokmG'),
(140,'Chill Select, Trell Daniels','Jazz','Lofi Jazz','Interstate 5','4QVaAn19v5fiuwcDE5OyKN'),
(141,'Chill Select,J Fletch, Toti Cisneros','Jazz','Lofi Jazz','Smooth As Butter','7s7g7qwKCC7ALhQS2GBAoq'),
(142,'Deftones','Metal','Metal Covers','Please Please Please Let Me Get What I Want - 2005 Remaster','4HpIh5wWfkq5sSuCLLSwYR'),
(143,'Like A Storm','Metal','Metal Covers','Gangsters Paradise','6xPD22JavtFYbyHl2AMVsn'),
(144,'Type O Negative','Metal','Metal Covers','Cinnamon Girl','1z9rTmGfW46p4eXimajRwV'),
(145,'Metallica','Metal','Metal Covers','Whiskey In The Jar','2R6UrJ8uWbSIiHWmvRQvN8'),
(146,'Five Finger Death Punch','Metal','Metal Covers','House of The Rising Sun','4ZmX8elKMkH0MfniNi0Adu'),
(147,'Bad Omens','Metal','Metal Mix','Careful What You Wish For','2gtmkmCRxmQFAr2xOPTdBo'),
(148,'Megadeth','Metal','Metal Mix','Holy Wars...The Punishment Due - 2004 Remix','5LyRtsQLhcXmy50VXhQXXS'),
(149,'Motörhead','Metal','Metal Mix','Overkill','3Staqm5EYDnYBqcwuxrWjZ'),
(150,'Black Sabbath','Metal','Metal Mix','Children of the Grave - Remastered Version','3ZuVfQriS93y6ofwbIf7lp'),
(151,'Accept','Metal','Metal Mix','Fast as a Shark','204523f9MSgEfc0oDJycNS'),
(152,'Tammy Wynette','Country','Old Country Songs','Stand By Your Man','6xatfNMI8NkY5XxRHAeiS4'),
(153,'Keith Whitley','Country','Old Country Songs','When You Say Nothing at All','1G60o2g78glgxC0No8SsvQ'),
(154,'Trisha Yearwood','Country','Old Country Songs','She\'s In Love With The Boy','2ulBBx6YQ3qY3ci34RadtN'),
(155,'Trace Adkins','Country','Old Country Songs','Every Light In The House','2A7j0RLnzvvlUFrevBiOQf'),
(156,'Alan Jackson','Country','Old Country Songs','Chattahoochee','59kHPbwyyCApYA8RQQEuXm'),
(157,'Deana Carter','Country','Old Country Songs','Strawberry Wine','5Pgwi0iizu96RHxJ4xL3SH'),
(158,'My Chemical Romance','Punk','Pink Punk','I\'m Not Okay (I Promise)','7lRlq939cDG4SzWOF4VAnd'),
(159,'Yellowcard','Punk','Pink Punk','Lights And Sounds','4XOZaPYeMn9hcbpyS90NnD'),
(160,'All Time Low','Punk','Pink Punk','Dear Maria, Count Me In','0JJP0IS4w0fJx01EcrfkDe'),
(161,'New Found Glory','Punk','Pink Punk','My Friends Over You','4pImG3RdbaGfanzQOTFgyr'),
(162,'We The Kings','Punk','Pink Punk','Check Yes, Juliet','0wVluBsVAVzBKrqspuCcwR'),
(163,'Lil Nas X','Pop','Pop  Songs Everyone Knows','Old Town Road','0F7FA14euOIX8KcbEturGH'),
(164,'The Chainsmokers','Pop','Pop  Songs Everyone Knows','Something Just Like This - Don Diablo Remix','15MTd64KUMG7CF6mOyovsQ'),
(165,'Taylor Swift','Pop','Pop  Songs Everyone Knows','I Knew You Were Trouble.','3lKZf71jeNi14udIFPJ29V'),
(166,'Nate Ruess, P!nk','Pop','Pop  Songs Everyone Knows','Just Give Me a Reason (feat. Nate Ruess)','1mKXFLRA179hdOWQBwUk9e'),
(167,'Katy Perry','Pop','Pop  Songs Everyone Knows','Last Friday Night (T.G.I.F.)','3oHNJECGN3bBoGXejlw2b1'),
(168,'Aqua, Ice Spice, Nicki Minaj','Pop','Pop Hits 2023','Barbie World (with Aqua) [From Barbie The Album]','2tQG2nFEHhWsH05kFKlC4A'),
(169,'Miley Cyrus','Pop','Pop Hits 2023','Flowers','4DHcnVTT87F0zZhRPYmZ3B'),
(170,'Em Beihold, Stephen Sanchez','Pop','Pop Hits 2023','Until I Found You (with Em Beihold) - Em Beihold Version','1Y3LN4zO1Edc2EluIoSPJN'),
(171,'SZA','Pop','Pop Hits 2023','Kill Bill','3OHfY25tqY28d16oZczHc8'),
(172,'Doja Cat, Post Malone','Pop','Pop Hits 2023','I Like You (A Happier Song) (with Doja Cat)','0O6u0VJ46W86TxN9wgyqDj'),
(173,'Bruno Mars','Pop','Pop Hits in 2000s- Throwback Vibes','Marry You','6SKwQghsR8AISlxhcwyA9R'),
(174,'Carly Rae Jepsen','Pop','Pop Hits in 2000s- Throwback Vibes','Call Me Maybe','20I6sIOMTCkB6w7ryavxtO'),
(175,'Britney Spears','Pop','Pop Hits in 2000s- Throwback Vibes','Gimme More','6ic8OlLUNEATToEFU3xmaH'),
(176,'Lady Gaga','Pop','Pop Hits in 2000s- Throwback Vibes','Poker Face','1QV6tiMFM6fSOKOGLMHYYg'),
(177,'Westlife','Pop','Pop Hits in 2000s- Throwback Vibes','Uptown Girl - Radio Edit','2sFp6E7lNBbblJGmUtCfFH'),
(178,'Lady Gaga','Pop','Pop Mix','Bad Romance','0SiywuOBRcynK0uKGWdCnn'),
(179,'Britney Spears','Pop','Pop Mix','...Baby One More Time','3MjUtNVVq3C8Fn0MP3zhXa'),
(180,'Katy Perry','Pop','Pop Mix','California Gurls','3f7gYMirBEKuc57218BjOY'),
(181,'Demi Lovato','Pop','Pop Mix','Cool for the Summer','3uwnnTQcHM1rDqSfA4gQNz'),
(182,'Olivia Rodrigo','Pop','Pop Mix','vampire','3k79jB4aGmMDUQzEwa46Rz'),
(183,'Stellar Kart','Punk','Punk Goes Disney','Do You Want to Build a Snowman?','7FhM8v76SFt7HJwo8fz5Aj'),
(184,'Stellar Kart','Punk','Punk Goes Disney','Let It Go','1Ug95kzSGgrfJftXK0AEXw'),
(185,'Peabo Bryson','Punk','Punk Goes Disney','A Whole New World (Aladdin\'s Theme)','7fLkHVJAJLENmSvhrEHZxV'),
(186,'Randy Newman','Punk','Punk Goes Disney','You\'ve Got a Friend in Me - From \"Toy Story\"','2stkLJ0JNcXkIRDNF3ld6c'),
(187,'Boy Hero','Punk','Punk Goes Disney','How Far I\'ll Go','6HEUVDkW2nPdP35MdS6xQj'),
(188,'AARCADE','Punk','Punk Goes Pop 2023 Lates Hits','Snake Eyes','6HEUVDkW2nPdP35MdS6xQj'),
(189,'Loveless','Punk','Punk Goes Pop 2023 Lates Hits','MIDDLE OF THE NIGHT','1Gwu3d6lZjL99kw4dcFCsq'),
(190,'Rain Paris','Punk','Punk Goes Pop 2023 Lates Hits','Golden Hour','5HIsWvuewNjRn4XmfBsLtf'),
(191,'Telescreens','Punk','Punk Goes Pop 2023 Lates Hits','Phone Booth','221dIk4DHWGGLNzlQmmOwG'),
(192,'Points of Conception','Punk','Punk Goes Pop 2023 Lates Hits','My City','7KuOA3m8zuae1BJRZ03obs'),
(193,'Real Friends','Punk','Punk Unplugged','Tell Me You\'re Sorry - Acoustic','3XNMVsuR5A5HqSsG4xMSYQ'),
(194,'Avril Lavigne','Punk','Punk Unplugged','Bite Me - Acoustic','71BPElgdb5MtfIJYGuTWqB'),
(195,'The Story So Far','Punk','Punk Unplugged','Clairvoyant','0nMOZnZA4GnipZXswSmCS6'),
(196,'A Day To Remember','Punk','Punk Unplugged','If It Means A Lot To You','3rEwGRmPVVudVjqdgv0tRR'),
(197,'Adjust the Sails','Punk','Punk Unplugged','Sobriety','11dGDlBXwgeY4umcI6Y8TT'),
(198,'Måneskin, Tom Morello','Rock','Rock 2023 International','GOSSIP (feat. Tom Morello)','4GvPlSOKfN7aXEuGW8zKUx'),
(199,'Bring Me The Horizon','Rock','Rock 2023 International','LosT','5BgnL6gHauuvxe4Ok6W1aC'),
(200,'Foo Fighters','Rock','Rock 2023 International','Rescued','6mgzUNNr3NY6NbTzNzwYq9'),
(201,'Måneskin','Rock','Rock 2023 International','I WANNA BE YOUR SLAVE','4pt5fDVTg5GhEvEtlz9dKk'),
(202,'Coyote Theory','Rock','Rock 2023 International','This Side of Paradise','79EkGysjP2dL5GdpeQjRxT');
